name: Merge to develop comment action

on:
  # check_suite:
  #   types: [completed]
  
    types: 

jobs:
  check_reaction:
    name: check_reaction
    runs-on: ubuntu-latest
    if: contains(github.head_ref, 'release/v')
    steps:
      - name: fetch latest comment id
        id: fetch_comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        with:
          script: |
            const response = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            })
            if (!response.data.length) {
              process.exit(0)
            }
            const comment = response.data.find((comment) => comment.user.login === 'github-actions[bot]')
            const commentId = comment.id
            return commentId
          result-encoding: string

      - name: comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        env:
          COMMENT_ID: "${{ steps.fetch_comment.outputs.result }}"
        with:
          script: |
            const env = process.env
            const response = await github.rest.issues.listForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: env.COMMENT_ID
            })
            console.log(response)
