name: Merge to develop comment action

on:
  # check_suite:
  #   types: [completed]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  comment_to_pr:
    name: comment_to_pr
    runs-on: ubuntu-latest
    environment: 
      name: production
    if: contains(github.head_ref, 'release/v')
    steps:
      - name: comment
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 #v6.4.1
        env:
          MESSAGE: |
            If you want to merge this PR into develop.
            Please comment these string.
            ```text
            🚀 Merge PR(#${{ github.event.number }}) into develop
            ```
            ${{ secrets.SAMPLE_SECRET}}
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: process.env.MESSAGE
            })
